name: Scrape Taiwan Earnings

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs on the 1st of every month at 00:00 UTC
  workflow_dispatch:     # Allows manual run from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium openpyxl

      - name: Run scraper
        run: python taiwan_no_api.py

      - name: Commit and push updated Excel file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Taiwan.xlsx
          git commit -m "Update Taiwan.xlsx from scraper run" || echo "No changes to commit"
          git push
