name: Update Taiwan CSV

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs every day at midnight UTC
  workflow_dispatch:     # Allows manual trigger from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium

      - name: Run the script
        run: python taiwam_no_api.py

      - name: Commit updated Taiwan.csv
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Taiwan.csv
          git commit -m "Auto-update Taiwan.csv"
          git push
